export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const SIGNIN_SUCCESS = 'SIGNIN_SUCCESS';
export const SIGNOUT_SUCCESS = 'SIGNOUT_SUCCESS';
export const FETCH_USER = 'FETCH_USER';

export const MESSAGE_DELETED = 'MESSAGE_DELETED';

export const NAV_CLICKED = 'NAV_CLICKED';
export const HOMEPAGE_VISITED = 'HOMEPAGE_VISITED';
export const USER_LOGGED_IN = 'USER_LOGGED_IN';
export const USER_LOGGED_OUT = 'USER_LOGGED_OUT';
export const SUBMITTING_FORM = 'SUBMITTING_FORM';
export const COMMENT_VIEWED = 'COMMENT_VIEWED';
